version: '3'
services:
  database:
    container_name: data_processing_database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_processing
    ports:
      - 3306:3306

  application_producer:
    container_name: data_processing_producer
    build: application-producer/
    environment:
      MYSQL_HOST: database
    ports:
      - 8080:8080
    depends_on:
      - database
